/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package piano;
import processing.core.PImage;

import static org.junit.Assert.assertFalse;

import org.junit.Test;

public class BlockTest {
    
    @Test
    public void blockCreation() {
        PImage testImage = new PImage();
        Block b = new Block(1,2,testImage);
        assert(b != null);
    }

    @Test
    public void blockStateToggle() {
        PImage testImage = new PImage();
        Block b = new Block(1,2,testImage);
        assert(!b.isActive());
        b.toggleState();
        assert(b.isActive());
        b.toggleState();
        assertFalse(b.isActive());
    }

    @Test 
    public void blockStateActivateAndDeactivate() {
        PImage testImage = new PImage();
        Block b = new Block(1,2,testImage);
        assert(!b.isActive());
        b.activate();
        assert(b.isActive());
        b.deactivate();
        assert(!b.isActive());
    }
}
